version: '3.7'

services:

  airbnb-res:
    build: ./
    working_dir: /Users/samjohnson/Documents/hrfiles/airbrb/reservation
    ports:
      - "5000:5000"
    expose:
      - 5000
    links:
      - "db"
    command: ["wait-for-it.sh", "db:3306", "--", "npm", "start"]
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
      - ./:/Users/samjohnson/Documents/hrfiles/airbrb/reservation

  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=airbrbRes
      - MYSQL_ROOT_PASSWORD=null
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - ./server/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: --default-authentication-plugin=mysql_native_password