version: '3.3'

services:

  airbnb-res:
    restart: on-failure
    build: ./
    working_dir: /Users/samjohnson/Documents/hrfiles/airbrb/reservation
    ports:
      - "5000:5000"
    links:
      - "db"
    command: bash -c "wait-for-it.sh db:3306 && npm install && npm run seed && npm run start"
    volumes:
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
      - ./:/Users/samjohnson/Documents/hrfiles/airbrb/reservation

  db:
    restart: always
    image: mysql:8
    environment:
      - MYSQL_DATABASE=airbrbRes
      - MYSQL_ROOT_PASSWORD=null
    ports:
      - "3306:3306"
    volumes:
      - ./server/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: --default-authentication-plugin=mysql_native_password